#!/usr/bin/env bash
# start-5199.sh — bring up the omp-web test instance on 5199 (LAN-exposed).
#
# Usage:  bash apps/omp-web/test/start-5199.sh [port]     (default 5199)
#
# Notes (2026-09-09, learned the hard way):
# - CLI `--port` is OVERRIDDEN by the test profile's cordis.patch.yml
#   `webserver.port: 4999`; a port move must go through a `--patch` overlay.
# - A patch row is RESTATED WHOLE: an overlay that only writes `port` drops
#   the row's `host: !!js ctx.webStartup.host ?? '127.0.0.1'` expression and
#   the boot dies with `$.host missing required value`. Carry host along.
# - LAN exposure: the overlay sets host 0.0.0.0. The dsh trust fence still
#   applies to non-loopback page origins — use the loopback token URL below
#   from this machine to authenticate, or pass --trusted-host for your LAN
#   origin if you want the page itself trusted remotely.
# - Teardown: systemctl --user stop omp-web-5199-test   (never kill).

set -euo pipefail

PORT="${1:-5199}"
UNIT="omp-web-5199-test"
LOG="$HOME/workspaces/dsh-omp/.scratch/omp-web-5199.log"
OVERLAY="$HOME/workspaces/dsh-omp/.scratch/port-${PORT}-lan.patch.yml"
DSH_BIN="/opt/node-v22.23.2/bin/node"
DSH="/home/u1/.local/bin/dsh"

# fail loudly if the target port is already taken
if ss -tln | grep -q ":${PORT} "; then
  echo "refusing to start: port ${PORT} already listening:" >&2
  ss -tlnp | grep ":${PORT} " >&2 || true
  exit 1
fi

# make sure the newest artifacts are what runs
cd "$(dirname "$0")/.."
npm run build >/dev/null
npm run build-client >/dev/null

cat > "$OVERLAY" <<EOF
# generated by start-5199.sh — port move + LAN bind (whole-row restatement)
- id: webserver
  config:
    host: !!js ctx.webStartup.host ?? '0.0.0.0'
    port: ${PORT}
EOF

# transient units linger after failure; clear any stale one first
systemctl --user reset-failed "$UNIT" 2>/dev/null || true

systemd-run --user --unit="$UNIT" \
  --property=WorkingDirectory="$HOME/.omp/omp-web" \
  --property=Environment=DSH_HOME="$HOME/.omp/omp-web" \
  --property=StandardOutput=append:"$LOG" \
  --property=StandardError=append:"$LOG" \
  "$DSH_BIN" "$DSH" --profile omp-web-test --patch "$OVERLAY" --no-open

# boot can take well over 10s (sidecar, model discovery); poll instead
ok=""
for _ in $(seq 1 30); do
  sleep 2
  if ss -tln | grep -q ":${PORT} "; then ok=1; break; fi
  systemctl --user is-active --quiet "$UNIT" || { journalctl --user -u "$UNIT" --no-pager | tail -20; exit 1; }
done
[ -n "$ok" ] || { echo "timeout waiting for ${PORT} to listen" >&2; exit 1; }

TOK=$(grep -o 'http://127.0.0.1:'"${PORT}"'/?token=[^" ]*' "$LOG" | tail -1 | grep -o 'token=.*' | cut -d= -f2)
[ -n "$TOK" ] || { echo "no token found in $LOG" >&2; exit 1; }
LAN_IP=$(hostname -I | awk '{print $1}')
echo "unit:   $UNIT (active)"
echo "lan:    http://${LAN_IP}:${PORT}/?token=${TOK}"
echo "local:  http://127.0.0.1:${PORT}/?token=${TOK}"
