#!/usr/bin/env bash
# start-4999.sh — bring up the omp-web Dev/Test instance (LAN-exposed).
#
# Usage:  bash test/start-4999.sh               # canonical 4999, LAN-exposed
#         PORT=4988 bash test/start-4999.sh     # override port
#         LAN=0 bash test/start-4999.sh         # loopback only (no relay)
#
# dsh web refuses `--host 0.0.0.0` (upstream RCE safety gate), so LAN access
# rides a user-space socat relay that binds the LAN IP only — never 0.0.0.0,
# which would collide with the loopback listener on the same port (EADDRINUSE).
# `--trusted-host <LAN_IP>` lets the /api browser-trust fence accept the relayed
# Host header (port-less host = any port). No public network / Caddy needed.
#
# Modeled on dashr test/start-4999.sh (proven 2026-09-06), adapted to the
# omp-web profile (global 0.1.5-rc.2 dsh binary, DSH_HOME=~/.omp/omp-web,
# profile omp-web-test). The launcher passes DSH_HOME + the profile name and
# nothing else: the plugin derives OMP_HOME=<DSH_HOME>/agents/omp for the SDK
# app home, and reads the operator's native ~/.omp for config/models.
#
# Teardown (never kill):
#   systemctl --user stop omp-web-<port>-test omp-web-lan-<port>-relay

set -euo pipefail

PORT="${PORT:-4999}"
LAN="${LAN:-1}"
UNIT="omp-web-${PORT}-test"
RELAY="omp-web-lan-${PORT}-relay"
PROFILE="omp-web-test"
DSH_HOME="$HOME/.omp/omp-web"
REPO="$HOME/workspaces/dsh-omp"
LOG="$REPO/.scratch/omp-web-${PORT}.log"
DSH_BIN="/home/u1/.local/bin/dsh"
NODE_BIN="/opt/node-v22.23.2/bin/node"
LAN_IP=$(hostname -I | awk '{print $1}')

mkdir -p "$REPO/.scratch"

# stop our own stale units first, then reset-failed (a leftover relay holding
# the port would otherwise trip the foreign-process refusal below)
systemctl --user stop "$UNIT" "$RELAY" 2>/dev/null || true
systemctl --user reset-failed "$UNIT" "$RELAY" 2>/dev/null || true
# node drains the socket after stop (session flush); a fixed sleep races it
# into EADDRINUSE — poll until the port is truly free
for _ in $(seq 1 15); do
  ss -tln | grep -q ":${PORT} " || break
  sleep 1
done
if ss -tln | grep -q ":${PORT} "; then
  echo "refusing to start: port ${PORT} still listening (foreign process):" >&2
  ss -tlnp | grep ":${PORT} " >&2 || true
  exit 1
fi

# append-mode log: remember the pre-start size so the token grep cannot capture
# a PREVIOUS boot's line
LOG_LINES=$( (wc -l < "$LOG") 2>/dev/null || echo 0 )

# Port override: the test profile's cordis.patch.yml pins `webserver.port: 4999`,
# so a non-default PORT needs a --patch overlay restating the WHOLE webserver
# row (host expression included) — a partial row drops `host` and dies with
# "host missing required value".
OVERLAY=""
if [ "$PORT" != "4999" ]; then
  OVERLAY="$REPO/.scratch/omp-web-${PORT}-port.patch.yml"
  cat > "$OVERLAY" <<EOF
# generated by start-4999.sh — port move (whole-row restatement)
- id: webserver
  config:
    host: !!js ctx.webStartup.host ?? '127.0.0.1'
    port: ${PORT}
EOF
fi

# The dsh instance — global 0.1.5-rc.2 binary, prod-aligned. Loopback bind only
# (the relay adds the LAN IP); --trusted-host carries the LAN IP so the relayed
# Host passes the /api fence. Unset GUI env so the web app never tries a
# browser open despite --no-open.
systemd-run --user --unit="$UNIT" \
  -p WorkingDirectory="$DSH_HOME" \
  -p Environment="DSH_HOME=$DSH_HOME" \
  -p Environment="DSH_TELEMETRY_DISABLED=1" \
  -p 'UnsetEnvironment=DISPLAY WAYLAND_DISPLAY' \
  -p StandardOutput=append:"$LOG" \
  -p StandardError=append:"$LOG" \
  "$NODE_BIN" "$DSH_BIN" --profile "$PROFILE" --no-open \
    --trusted-host "$LAN_IP" \
    ${OVERLAY:+--patch "$OVERLAY"}

# boot can take a while (OMP bridge, model discovery); poll for the loopback
# listener BEFORE starting the relay (relay binds instantly, dsh binds late)
ok=""
for _ in $(seq 1 30); do
  sleep 2
  if ss -tln | grep -q "127.0.0.1:${PORT} "; then ok=1; break; fi
  systemctl --user is-active --quiet "$UNIT" || { tail -30 "$LOG" >&2; exit 1; }
done
[ -n "$ok" ] || { echo "timeout waiting for 127.0.0.1:${PORT} to listen" >&2; exit 1; }

if [ "$LAN" = "1" ]; then
  # LAN relay: ${LAN_IP}:${PORT} → 127.0.0.1:${PORT} (bind the LAN IP ONLY —
  # a wildcard 0.0.0.0 same-port bind collides with the loopback listener).
  # The browser's Host header (LAN_IP:PORT) passes the fence via --trusted-host
  # above; the auth cookie binds host:port, consistent end to end.
  systemd-run --user --unit="$RELAY" \
    -p StandardOutput=append:"$LOG" \
    -p StandardError=append:"$LOG" \
    /usr/bin/socat "TCP-LISTEN:${PORT},fork,reuseaddr,bind=${LAN_IP}" "TCP:127.0.0.1:${PORT}"

  for _ in $(seq 1 10); do
    ss -tln | grep -q "${LAN_IP}:${PORT} " && break
    sleep 1
  done
  ss -tln | grep -q "${LAN_IP}:${PORT} " || { echo "socat relay not listening on ${LAN_IP}:${PORT}" >&2; exit 1; }
else
  ss -tln | grep -q "0.0.0.0:${PORT} " && { echo "refusing: port ${PORT} wildcard-occupied but LAN=0" >&2; exit 1; }
fi

# THIS boot's token only (tail past the pre-start line count). The URL line
# flushes shortly AFTER the listener binds — poll for it instead of racing.
TOK=""
for _ in $(seq 1 15); do
  TOK=$( { tail -n +"$((LOG_LINES + 1))" "$LOG" | grep -o "http://127.0.0.1:${PORT}/?token=[^\" ]*" | tail -1 | grep -o 'token=.*' | cut -d= -f2; } 2>/dev/null || true)
  [ -n "$TOK" ] && break
  sleep 1
done
[ -n "$TOK" ] || { echo "no token found in $LOG (this boot)" >&2; exit 1; }

echo "unit:   $UNIT (active)$([ "$LAN" = "1" ] && echo " + $RELAY (active)")"
[ "$LAN" = "1" ] && echo "lan:    http://${LAN_IP}:${PORT}/?token=${TOK}"
echo "local:  http://127.0.0.1:${PORT}/?token=${TOK}"
